### ISSUE TITLE
demo编辑视频报错:Can't create handler inside thread that has not called Looper.prepare()

### ISSUE THREAD

**Issue by zsfzbc** [yangjie10930/EpMediaDemo#12]
```
E/AndroidRuntime: FATAL EXCEPTION: Thread-47370
    Process: com.joe.epmediademo, PID: 20826
    java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
        at android.os.Handler.<init>(Handler.java:209)
        at android.os.Handler.<init>(Handler.java:123)
        at android.widget.Toast$TN.<init>(Toast.java:360)
        at android.widget.Toast.<init>(Toast.java:105)
        at android.widget.Toast.makeText(Toast.java:270)
        at com.joe.epmediademo.Activity.MergeActivity$1.onSuccess(MergeActivity.java:101)
        at VideoHandle.EpEditor$2.onSuccess(EpEditor.java:574)
        at Jni.FFmpegCmd.onExecuted(FFmpegCmd.java:48)
```

**Comment by yangjie10930** [comment]
回调里的问题吧，子线程handler没looper，稍微改下
